import { environment } from '../../environments/environment';

export const Constantes = {

    // CONST_ENDPOINT_PROXY                    : environment.url_proxy,//NECESARIA PARA PRIMER CARGUE PROPIEDADES
    // PROP_ENDPOINT_BIOMETRIA_VOZCONST_ENDPOINT_SER_GENERAL               : environment.url_sergeneral,//NECESARIA PARA REGISTRO LOGS
    PROP_ENDPOINT_CONSULTAR_SITIOS           : 'app.endpoint.consultar.sitios.habilitados',
    PROP_ENDPOINT_CONSULTAR_PANTALLAS        : 'app.endpoint.consultar.pantallas.habilitadas',
    PROP_ENDPOINT_FIDELIZACION_PREPAGO       : "app.endpoint.fidelizacion.prepago",
    CONST_ENDPOINT_OPENSHIFT               : environment.url_biblioteca,//NECESARIA PARA REGISTRO LOGS
    PROP_ENDPOINT_BIOMETRIA_VOZ      : "app.endpoint.biometria.voz",
    PROP_ENDPOINT_BIOMETRIA_VOZ_DELETE      : "app.endpoint.biometria.voz.delete",
    PROP_ENDPOINT_BIOMETRIA_VOZ_CONSULTA      : "app.endpoint.biometria.voz.consulta",
    PROP_TIPO_DOCUMENTO_BIOMETRIA_VOZ      : "app.tipo.documento.biometria.voz",
    PROP_TIPO_USUARIO_BIOMETRIA_VOZ      : "app.tipo.usuario.biometria.voz",
    PROP_SEPARADOR_DOCUMENTO_BIOMETRIA_VOZ      : "app.separador.documento.biometria.voz",
    PROP_BIOMETRIA_GENERO_MASCULINO        :"app.biometria.genero.masculino",
    PROP_BIOMETRIA_GENERO_FEMENINO       :"app.biometria.genero.femenimo",
    PROP_BIOMETRIA_BODY_ELIMINAR_HUELLA_VOZ       :"app.biometria.body.eliminar.huella.voz",
    PROP_BIOMETRIA_BODY_VALIDACION_HUELLA_VOZ       :"app.biometria.body.validacion.huella.voz",
    PROP_ENDPOINT_BIOMETRIA_VOZ_ELASTIC     : "app.endpoint.biometria.voz.elastic",
    PROP_BIOMETRIA_VOZ_ATTHORIZATION_ELASTIC    : "app.biometria.voz.authorization.elastic",
    PROP_ENDPOINT_LOGIN                      : "app.endpoint.login",
    PROP_ENDPOINT_WS_LINES_PBX               : "app.endpoint.ws.lines.pbx",
    PROP_PBX_LINES_USER_FTP         : "app.pbx.user.ftp",
    PROP_PBX_LINES_HOST_FTP         : "app.pbx.host.ftp",
    PROP_PBX_LINES_PASS_FTP         : "app.pbx.pass.ftp",
    PROP_PBX_LINES_PATH_FTP         : "app.pbx.path.ftp",
    PROP_PBX_LINES_ESTADO_ACTIVO_ZONAS      : "ACTIVA",
    PROP_PBX_LINES_ESTADO_CARGUE_MASIVO     : "app.pbx.estado.cargue.masivo",
    PROP_PBX_LINES_TAMANO_MAX_ARCHIVO_CARGUE : "app.pbx.tamano.max.archivo.cargue",
    PROP_TEXTO_MODAL_AYUDA          : "app.texto.modal.ayuda",
    PROP_ENDPOINT_REGISTROIMEI      : "app.endpoint.registroimei",
    TRUE                            : "true",
    USUARIO                         : "usuario",
    TIEMPO_EXPIRACION               : 5,
    CANAL_APLICACION                : "APP_CANAL_BIOMETRIA_VOZ",
    NOMBRE_APLICACION               : "APP_OPENSHIFT",
    PROP_TAMANO_PAGINA              : "10",
    PATRON_SOLO_DIGITOS             :/^([0-9])*$/,
    RUTA_IMG_X_DEFECTO              : './assets/img/lapiz.png',
    CONST_SITIO_ACTUAL              : 'SitioActual',
    CONST_PANTALLAS_HABILITADAS     : 'pantallasHabilitadas',
    CONST_IS_HABILITADO_SITIO_ACTUAL: 'isHabilitadoSitioActual',
    HTTP_STATUS_CODE_500            :500,
    HTTP_STATUS_MSJ_500             :'Error Interno',
    CONST_ACCION_CONSULTAR          : "c",
    CONST_ACCION_INSERTAR           : "i",
    CONST_ACCION_ACTUALIZAR         : "a",
    CONST_ACCION_ELIMINAR           : "e",
    CONST_CODIGO_RESP_EXITOSO       : 0,
    CONST_FORMATO_FECHA_T             : "yyyy-MM-ddTHH:mm:ss",
    PAIS_FORMATO_FECHA_EN_US              : "en-US",
    CONST_RUTA_URL_LOGS             : '/logs/guardar',
    CONST_RUTA_URL_AMD_SITIOS       : '/sitios/admSitiosEAF',
    CONST_CANT_BYTES_X_MB           : "1048576",
    CONST_ENDPOINT_REGIST_IMEI      : "/registroIMEI/crudRegistroIMEI",
    CONST_ENDPOINT_HOM_MSG          : "/homMsg/crudHomologacionMsg",
    CONST_TIMEOUT_GENERAL           : "app.timeout.general",
    CONST_TIMEOUT_INACTIVIDAD       : "app.timeout.inactividad",
    CONST_TIPO_USUARIO              : "tipoUsuario",
    CONST_NIT_EMPRESA_USUARIO_LOGUEADO  : "nir_empresa_usuario_logueado",
    CONST_NOMBRE_USUARIO_LOGUEADO   : "nombre_usuario_logueado",
    CONST_NOMBRE_CLIENTE_USUARIO_LOGUEADO   : "nombre_cliente_usuario_logueado",
    CONST_ADMIN                     : "admin",
    CONST_USER                      : "user",
    PATRON_DIGITOS: /^[3]{1}\d{9}/,
    PATRON_CORREO: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,3}$/,
    PROP_REASON_HUELLA_VOZ          : "app.reason.huella.voz",
    PROP_REASON_DESC_HUELLA_VOZ     : "app.reason.desc.huella.voz",
    PROP_NAME_HUELLA_VOZ     : "app.name.huella.voz",
    EXCEL_TYPE:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8",
    EXCEL_EXTENSION:".xlsx",
    CONST_MENSAJE_CONFIRMAR_ELIMINACION: "¿Estás seguro que deseas eliminar el registro?",
    CONST_MENSAJE_CONFIRMAR_ALMACENAMIENTO:"¿Estás seguro que deseas guardar los datos del formulario?",
    CONST_TITULO_MENSAJES_CONFIRMACION:"¿Mensaje de confirmación?"
}
